import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className=" text-white ">
          <nav className=" bg-gray-950 fixed top-0 left-0 z-11 lg:flex justify-between pl-[100px] pr-[100px] lg:h-[60px] h-[80px] text-center m-auto  items-center w-full">
            <div className="logo text-[30px] hover:text-[#9a7bb9]">
              <span className="text-[#9a7bb9]">3D</span> COVER FLOW
            </div>
            <ul className="flex md:gap-[40px] gap-[10px] text-[20px]">
              <li className="hover:text-[#9a7bb9] relative after:content-[''] after:absolute after:left-1/2 after:bottom-0  after:h-[2px] after:w-0 after:bg-[#9a7bb9] after:transition-all after:duration-300 after:-translate-x-1/2 after:origin-center hover:after:w-full">
                <Link href={"/"}>Home</Link>
              </li>
              <li className="hover:text-[#9a7bb9] relative after:content-[''] after:absolute after:left-1/2 after:bottom-0  after:h-[2px] after:w-0 after:bg-[#9a7bb9] after:transition-all after:duration-300 after:-translate-x-1/2 after:origin-center hover:after:w-full">
                <Link href={"/users"}>Users</Link>
              </li>
              <li className="hover:text-[#9a7bb9] relative after:content-[''] after:absolute after:left-1/2 after:bottom-0  after:h-[2px] after:w-0 after:bg-[#9a7bb9] after:transition-all after:duration-300 after:-translate-x-1/2 after:origin-center hover:after:w-full">
                <Link href={"/posts"}>Posts</Link>
              </li>
              <li className="hover:text-[#9a7bb9] relative after:content-[''] after:absolute after:left-1/2 after:bottom-0  after:h-[2px] after:w-0 after:bg-[#9a7bb9] after:transition-all after:duration-300 after:-translate-x-1/2 after:origin-center hover:after:w-full">
                <Link href={"/todos"}>Todos</Link>
              </li>
              <li className="hover:text-[#9a7bb9] ">
                <Link href={"/login"}>
                  <button className="bg-[#9a7bb9] hover:bg-white transition-[.3s all ease-in] text-[17px ] px-[10px] lg:px-[30px] lg:py-[5px] lg:rounded-2xl rounded-[15px]">
                    Log In 
                  </button>
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="">{children}</main>
        {/* ********************************************** */}
        {/* start footer  */}
<footer className="footer  bg-gray-950 text-white h-[60px] w-full">
  <div className="footer-content flex items-center justify-between ml-[100px] h-full">
    <div className="footer-copyright">
      © 2025 3D Coverflow. All rights reserved. | Designed by{" "}
      <a
        href="https://templatemo.com"
        target="_blank"
        rel="noopener noreferrer"
      >
        TemplateMo
      </a>
    </div>

    <div className="footer-links mr-[100px]">
      <a href="#privacy">Privacy Policy </a>
      <a href="#terms">Terms of Service</a>
    </div>
  </div>
</footer>
      </body>
    </html>
  );
}
